services:
  - type: web
    name: my-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 24.11.1
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
