DATABASE_URL= mongodb+srv://maryamurshudlu_db_user:9aRtDC3IZUHO1I8o@myapi.0oiii59.mongodb.net/pokemon_api?retryWrites=true&w=majority&appName=MyAPI
JWT_SECRET=my_api_secret_2026_maryam_8472
BASE_URL=
REDIS_URL=

services:
  - type: web
    name: my-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 24.11.1
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
